  - name: Add floating IP
    os_floating_ip:
      cloud: ospcloud
      state: present
      reuse: yes
      server: "{{ item.value.name }}"
      network: ext_network
      wait: true
      timeout: 180
    register: instancefloatingip
    with_dict: "{{ osp_servers }}"

#  - name: Show Assigned Floating IP
#    debug: var=instancefloatingip
