---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  include_tasks: create-server.yml

- name: Add floating IP to Servers
  include_tasks: assign-ip.yml

- name: Wait for server to be available
  include_tasks: waitfor-server.yml
